<?php
    session_start();
    unset($_SESSION['apriori_skripsi_id']);
    unset($_SESSION['apriori_skripsi_username']);
    unset($_SESSION['apriori_skripsi_level']);
    unset($_SESSION['apriori_skripsi_key']);
    unset($_SESSION['apriori_skripsi_last_login']);
    session_destroy();
    header("location:login.php");
